package com.johnny.mybatis.pojo;

import java.util.Date;

public class ExternalLogInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMLM2_EXTERNAL_LOG_INFO.ID_AMLM2_EXTERNAL_LOG
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    private String idAmlm2ExternalLog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMLM2_EXTERNAL_LOG_INFO.REQUEST_DATA
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    private String requestData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMLM2_EXTERNAL_LOG_INFO.SERIES_CODE
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    private String seriesCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMLM2_EXTERNAL_LOG_INFO.REQUEST_URL
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    private String requestUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMLM2_EXTERNAL_LOG_INFO.REQUESET_METHOD
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    private String requesetMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMLM2_EXTERNAL_LOG_INFO.RESULT_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    private String resultInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMLM2_EXTERNAL_LOG_INFO.DESC_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    private String descInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMLM2_EXTERNAL_LOG_INFO.CREATED_BY
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMLM2_EXTERNAL_LOG_INFO.CREATED_DATE
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMLM2_EXTERNAL_LOG_INFO.UPDATED_BY
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMLM2_EXTERNAL_LOG_INFO.UPDATED_DATE
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    private Date updatedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMLM2_EXTERNAL_LOG_INFO.ID_AMLM2_EXTERNAL_LOG
     *
     * @return the value of AMLM2_EXTERNAL_LOG_INFO.ID_AMLM2_EXTERNAL_LOG
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public String getIdAmlm2ExternalLog() {
        return idAmlm2ExternalLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMLM2_EXTERNAL_LOG_INFO.ID_AMLM2_EXTERNAL_LOG
     *
     * @param idAmlm2ExternalLog the value for AMLM2_EXTERNAL_LOG_INFO.ID_AMLM2_EXTERNAL_LOG
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public void setIdAmlm2ExternalLog(String idAmlm2ExternalLog) {
        this.idAmlm2ExternalLog = idAmlm2ExternalLog == null ? null : idAmlm2ExternalLog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMLM2_EXTERNAL_LOG_INFO.REQUEST_DATA
     *
     * @return the value of AMLM2_EXTERNAL_LOG_INFO.REQUEST_DATA
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public String getRequestData() {
        return requestData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMLM2_EXTERNAL_LOG_INFO.REQUEST_DATA
     *
     * @param requestData the value for AMLM2_EXTERNAL_LOG_INFO.REQUEST_DATA
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public void setRequestData(String requestData) {
        this.requestData = requestData == null ? null : requestData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMLM2_EXTERNAL_LOG_INFO.SERIES_CODE
     *
     * @return the value of AMLM2_EXTERNAL_LOG_INFO.SERIES_CODE
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public String getSeriesCode() {
        return seriesCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMLM2_EXTERNAL_LOG_INFO.SERIES_CODE
     *
     * @param seriesCode the value for AMLM2_EXTERNAL_LOG_INFO.SERIES_CODE
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public void setSeriesCode(String seriesCode) {
        this.seriesCode = seriesCode == null ? null : seriesCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMLM2_EXTERNAL_LOG_INFO.REQUEST_URL
     *
     * @return the value of AMLM2_EXTERNAL_LOG_INFO.REQUEST_URL
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public String getRequestUrl() {
        return requestUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMLM2_EXTERNAL_LOG_INFO.REQUEST_URL
     *
     * @param requestUrl the value for AMLM2_EXTERNAL_LOG_INFO.REQUEST_URL
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl == null ? null : requestUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMLM2_EXTERNAL_LOG_INFO.REQUESET_METHOD
     *
     * @return the value of AMLM2_EXTERNAL_LOG_INFO.REQUESET_METHOD
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public String getRequesetMethod() {
        return requesetMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMLM2_EXTERNAL_LOG_INFO.REQUESET_METHOD
     *
     * @param requesetMethod the value for AMLM2_EXTERNAL_LOG_INFO.REQUESET_METHOD
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public void setRequesetMethod(String requesetMethod) {
        this.requesetMethod = requesetMethod == null ? null : requesetMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMLM2_EXTERNAL_LOG_INFO.RESULT_INFO
     *
     * @return the value of AMLM2_EXTERNAL_LOG_INFO.RESULT_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public String getResultInfo() {
        return resultInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMLM2_EXTERNAL_LOG_INFO.RESULT_INFO
     *
     * @param resultInfo the value for AMLM2_EXTERNAL_LOG_INFO.RESULT_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public void setResultInfo(String resultInfo) {
        this.resultInfo = resultInfo == null ? null : resultInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMLM2_EXTERNAL_LOG_INFO.DESC_INFO
     *
     * @return the value of AMLM2_EXTERNAL_LOG_INFO.DESC_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public String getDescInfo() {
        return descInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMLM2_EXTERNAL_LOG_INFO.DESC_INFO
     *
     * @param descInfo the value for AMLM2_EXTERNAL_LOG_INFO.DESC_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public void setDescInfo(String descInfo) {
        this.descInfo = descInfo == null ? null : descInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMLM2_EXTERNAL_LOG_INFO.CREATED_BY
     *
     * @return the value of AMLM2_EXTERNAL_LOG_INFO.CREATED_BY
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMLM2_EXTERNAL_LOG_INFO.CREATED_BY
     *
     * @param createdBy the value for AMLM2_EXTERNAL_LOG_INFO.CREATED_BY
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMLM2_EXTERNAL_LOG_INFO.CREATED_DATE
     *
     * @return the value of AMLM2_EXTERNAL_LOG_INFO.CREATED_DATE
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMLM2_EXTERNAL_LOG_INFO.CREATED_DATE
     *
     * @param createdDate the value for AMLM2_EXTERNAL_LOG_INFO.CREATED_DATE
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMLM2_EXTERNAL_LOG_INFO.UPDATED_BY
     *
     * @return the value of AMLM2_EXTERNAL_LOG_INFO.UPDATED_BY
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMLM2_EXTERNAL_LOG_INFO.UPDATED_BY
     *
     * @param updatedBy the value for AMLM2_EXTERNAL_LOG_INFO.UPDATED_BY
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMLM2_EXTERNAL_LOG_INFO.UPDATED_DATE
     *
     * @return the value of AMLM2_EXTERNAL_LOG_INFO.UPDATED_DATE
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMLM2_EXTERNAL_LOG_INFO.UPDATED_DATE
     *
     * @param updatedDate the value for AMLM2_EXTERNAL_LOG_INFO.UPDATED_DATE
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
}