package com.johnny.mybatis.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ExternalLogInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public ExternalLogInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdAmlm2ExternalLogIsNull() {
            addCriterion("ID_AMLM2_EXTERNAL_LOG is null");
            return (Criteria) this;
        }

        public Criteria andIdAmlm2ExternalLogIsNotNull() {
            addCriterion("ID_AMLM2_EXTERNAL_LOG is not null");
            return (Criteria) this;
        }

        public Criteria andIdAmlm2ExternalLogEqualTo(String value) {
            addCriterion("ID_AMLM2_EXTERNAL_LOG =", value, "idAmlm2ExternalLog");
            return (Criteria) this;
        }

        public Criteria andIdAmlm2ExternalLogNotEqualTo(String value) {
            addCriterion("ID_AMLM2_EXTERNAL_LOG <>", value, "idAmlm2ExternalLog");
            return (Criteria) this;
        }

        public Criteria andIdAmlm2ExternalLogGreaterThan(String value) {
            addCriterion("ID_AMLM2_EXTERNAL_LOG >", value, "idAmlm2ExternalLog");
            return (Criteria) this;
        }

        public Criteria andIdAmlm2ExternalLogGreaterThanOrEqualTo(String value) {
            addCriterion("ID_AMLM2_EXTERNAL_LOG >=", value, "idAmlm2ExternalLog");
            return (Criteria) this;
        }

        public Criteria andIdAmlm2ExternalLogLessThan(String value) {
            addCriterion("ID_AMLM2_EXTERNAL_LOG <", value, "idAmlm2ExternalLog");
            return (Criteria) this;
        }

        public Criteria andIdAmlm2ExternalLogLessThanOrEqualTo(String value) {
            addCriterion("ID_AMLM2_EXTERNAL_LOG <=", value, "idAmlm2ExternalLog");
            return (Criteria) this;
        }

        public Criteria andIdAmlm2ExternalLogLike(String value) {
            addCriterion("ID_AMLM2_EXTERNAL_LOG like", value, "idAmlm2ExternalLog");
            return (Criteria) this;
        }

        public Criteria andIdAmlm2ExternalLogNotLike(String value) {
            addCriterion("ID_AMLM2_EXTERNAL_LOG not like", value, "idAmlm2ExternalLog");
            return (Criteria) this;
        }

        public Criteria andIdAmlm2ExternalLogIn(List<String> values) {
            addCriterion("ID_AMLM2_EXTERNAL_LOG in", values, "idAmlm2ExternalLog");
            return (Criteria) this;
        }

        public Criteria andIdAmlm2ExternalLogNotIn(List<String> values) {
            addCriterion("ID_AMLM2_EXTERNAL_LOG not in", values, "idAmlm2ExternalLog");
            return (Criteria) this;
        }

        public Criteria andIdAmlm2ExternalLogBetween(String value1, String value2) {
            addCriterion("ID_AMLM2_EXTERNAL_LOG between", value1, value2, "idAmlm2ExternalLog");
            return (Criteria) this;
        }

        public Criteria andIdAmlm2ExternalLogNotBetween(String value1, String value2) {
            addCriterion("ID_AMLM2_EXTERNAL_LOG not between", value1, value2, "idAmlm2ExternalLog");
            return (Criteria) this;
        }

        public Criteria andRequestDataIsNull() {
            addCriterion("REQUEST_DATA is null");
            return (Criteria) this;
        }

        public Criteria andRequestDataIsNotNull() {
            addCriterion("REQUEST_DATA is not null");
            return (Criteria) this;
        }

        public Criteria andRequestDataEqualTo(String value) {
            addCriterion("REQUEST_DATA =", value, "requestData");
            return (Criteria) this;
        }

        public Criteria andRequestDataNotEqualTo(String value) {
            addCriterion("REQUEST_DATA <>", value, "requestData");
            return (Criteria) this;
        }

        public Criteria andRequestDataGreaterThan(String value) {
            addCriterion("REQUEST_DATA >", value, "requestData");
            return (Criteria) this;
        }

        public Criteria andRequestDataGreaterThanOrEqualTo(String value) {
            addCriterion("REQUEST_DATA >=", value, "requestData");
            return (Criteria) this;
        }

        public Criteria andRequestDataLessThan(String value) {
            addCriterion("REQUEST_DATA <", value, "requestData");
            return (Criteria) this;
        }

        public Criteria andRequestDataLessThanOrEqualTo(String value) {
            addCriterion("REQUEST_DATA <=", value, "requestData");
            return (Criteria) this;
        }

        public Criteria andRequestDataLike(String value) {
            addCriterion("REQUEST_DATA like", value, "requestData");
            return (Criteria) this;
        }

        public Criteria andRequestDataNotLike(String value) {
            addCriterion("REQUEST_DATA not like", value, "requestData");
            return (Criteria) this;
        }

        public Criteria andRequestDataIn(List<String> values) {
            addCriterion("REQUEST_DATA in", values, "requestData");
            return (Criteria) this;
        }

        public Criteria andRequestDataNotIn(List<String> values) {
            addCriterion("REQUEST_DATA not in", values, "requestData");
            return (Criteria) this;
        }

        public Criteria andRequestDataBetween(String value1, String value2) {
            addCriterion("REQUEST_DATA between", value1, value2, "requestData");
            return (Criteria) this;
        }

        public Criteria andRequestDataNotBetween(String value1, String value2) {
            addCriterion("REQUEST_DATA not between", value1, value2, "requestData");
            return (Criteria) this;
        }

        public Criteria andSeriesCodeIsNull() {
            addCriterion("SERIES_CODE is null");
            return (Criteria) this;
        }

        public Criteria andSeriesCodeIsNotNull() {
            addCriterion("SERIES_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andSeriesCodeEqualTo(String value) {
            addCriterion("SERIES_CODE =", value, "seriesCode");
            return (Criteria) this;
        }

        public Criteria andSeriesCodeNotEqualTo(String value) {
            addCriterion("SERIES_CODE <>", value, "seriesCode");
            return (Criteria) this;
        }

        public Criteria andSeriesCodeGreaterThan(String value) {
            addCriterion("SERIES_CODE >", value, "seriesCode");
            return (Criteria) this;
        }

        public Criteria andSeriesCodeGreaterThanOrEqualTo(String value) {
            addCriterion("SERIES_CODE >=", value, "seriesCode");
            return (Criteria) this;
        }

        public Criteria andSeriesCodeLessThan(String value) {
            addCriterion("SERIES_CODE <", value, "seriesCode");
            return (Criteria) this;
        }

        public Criteria andSeriesCodeLessThanOrEqualTo(String value) {
            addCriterion("SERIES_CODE <=", value, "seriesCode");
            return (Criteria) this;
        }

        public Criteria andSeriesCodeLike(String value) {
            addCriterion("SERIES_CODE like", value, "seriesCode");
            return (Criteria) this;
        }

        public Criteria andSeriesCodeNotLike(String value) {
            addCriterion("SERIES_CODE not like", value, "seriesCode");
            return (Criteria) this;
        }

        public Criteria andSeriesCodeIn(List<String> values) {
            addCriterion("SERIES_CODE in", values, "seriesCode");
            return (Criteria) this;
        }

        public Criteria andSeriesCodeNotIn(List<String> values) {
            addCriterion("SERIES_CODE not in", values, "seriesCode");
            return (Criteria) this;
        }

        public Criteria andSeriesCodeBetween(String value1, String value2) {
            addCriterion("SERIES_CODE between", value1, value2, "seriesCode");
            return (Criteria) this;
        }

        public Criteria andSeriesCodeNotBetween(String value1, String value2) {
            addCriterion("SERIES_CODE not between", value1, value2, "seriesCode");
            return (Criteria) this;
        }

        public Criteria andRequestUrlIsNull() {
            addCriterion("REQUEST_URL is null");
            return (Criteria) this;
        }

        public Criteria andRequestUrlIsNotNull() {
            addCriterion("REQUEST_URL is not null");
            return (Criteria) this;
        }

        public Criteria andRequestUrlEqualTo(String value) {
            addCriterion("REQUEST_URL =", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlNotEqualTo(String value) {
            addCriterion("REQUEST_URL <>", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlGreaterThan(String value) {
            addCriterion("REQUEST_URL >", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlGreaterThanOrEqualTo(String value) {
            addCriterion("REQUEST_URL >=", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlLessThan(String value) {
            addCriterion("REQUEST_URL <", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlLessThanOrEqualTo(String value) {
            addCriterion("REQUEST_URL <=", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlLike(String value) {
            addCriterion("REQUEST_URL like", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlNotLike(String value) {
            addCriterion("REQUEST_URL not like", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlIn(List<String> values) {
            addCriterion("REQUEST_URL in", values, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlNotIn(List<String> values) {
            addCriterion("REQUEST_URL not in", values, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlBetween(String value1, String value2) {
            addCriterion("REQUEST_URL between", value1, value2, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlNotBetween(String value1, String value2) {
            addCriterion("REQUEST_URL not between", value1, value2, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequesetMethodIsNull() {
            addCriterion("REQUESET_METHOD is null");
            return (Criteria) this;
        }

        public Criteria andRequesetMethodIsNotNull() {
            addCriterion("REQUESET_METHOD is not null");
            return (Criteria) this;
        }

        public Criteria andRequesetMethodEqualTo(String value) {
            addCriterion("REQUESET_METHOD =", value, "requesetMethod");
            return (Criteria) this;
        }

        public Criteria andRequesetMethodNotEqualTo(String value) {
            addCriterion("REQUESET_METHOD <>", value, "requesetMethod");
            return (Criteria) this;
        }

        public Criteria andRequesetMethodGreaterThan(String value) {
            addCriterion("REQUESET_METHOD >", value, "requesetMethod");
            return (Criteria) this;
        }

        public Criteria andRequesetMethodGreaterThanOrEqualTo(String value) {
            addCriterion("REQUESET_METHOD >=", value, "requesetMethod");
            return (Criteria) this;
        }

        public Criteria andRequesetMethodLessThan(String value) {
            addCriterion("REQUESET_METHOD <", value, "requesetMethod");
            return (Criteria) this;
        }

        public Criteria andRequesetMethodLessThanOrEqualTo(String value) {
            addCriterion("REQUESET_METHOD <=", value, "requesetMethod");
            return (Criteria) this;
        }

        public Criteria andRequesetMethodLike(String value) {
            addCriterion("REQUESET_METHOD like", value, "requesetMethod");
            return (Criteria) this;
        }

        public Criteria andRequesetMethodNotLike(String value) {
            addCriterion("REQUESET_METHOD not like", value, "requesetMethod");
            return (Criteria) this;
        }

        public Criteria andRequesetMethodIn(List<String> values) {
            addCriterion("REQUESET_METHOD in", values, "requesetMethod");
            return (Criteria) this;
        }

        public Criteria andRequesetMethodNotIn(List<String> values) {
            addCriterion("REQUESET_METHOD not in", values, "requesetMethod");
            return (Criteria) this;
        }

        public Criteria andRequesetMethodBetween(String value1, String value2) {
            addCriterion("REQUESET_METHOD between", value1, value2, "requesetMethod");
            return (Criteria) this;
        }

        public Criteria andRequesetMethodNotBetween(String value1, String value2) {
            addCriterion("REQUESET_METHOD not between", value1, value2, "requesetMethod");
            return (Criteria) this;
        }

        public Criteria andResultInfoIsNull() {
            addCriterion("RESULT_INFO is null");
            return (Criteria) this;
        }

        public Criteria andResultInfoIsNotNull() {
            addCriterion("RESULT_INFO is not null");
            return (Criteria) this;
        }

        public Criteria andResultInfoEqualTo(String value) {
            addCriterion("RESULT_INFO =", value, "resultInfo");
            return (Criteria) this;
        }

        public Criteria andResultInfoNotEqualTo(String value) {
            addCriterion("RESULT_INFO <>", value, "resultInfo");
            return (Criteria) this;
        }

        public Criteria andResultInfoGreaterThan(String value) {
            addCriterion("RESULT_INFO >", value, "resultInfo");
            return (Criteria) this;
        }

        public Criteria andResultInfoGreaterThanOrEqualTo(String value) {
            addCriterion("RESULT_INFO >=", value, "resultInfo");
            return (Criteria) this;
        }

        public Criteria andResultInfoLessThan(String value) {
            addCriterion("RESULT_INFO <", value, "resultInfo");
            return (Criteria) this;
        }

        public Criteria andResultInfoLessThanOrEqualTo(String value) {
            addCriterion("RESULT_INFO <=", value, "resultInfo");
            return (Criteria) this;
        }

        public Criteria andResultInfoLike(String value) {
            addCriterion("RESULT_INFO like", value, "resultInfo");
            return (Criteria) this;
        }

        public Criteria andResultInfoNotLike(String value) {
            addCriterion("RESULT_INFO not like", value, "resultInfo");
            return (Criteria) this;
        }

        public Criteria andResultInfoIn(List<String> values) {
            addCriterion("RESULT_INFO in", values, "resultInfo");
            return (Criteria) this;
        }

        public Criteria andResultInfoNotIn(List<String> values) {
            addCriterion("RESULT_INFO not in", values, "resultInfo");
            return (Criteria) this;
        }

        public Criteria andResultInfoBetween(String value1, String value2) {
            addCriterion("RESULT_INFO between", value1, value2, "resultInfo");
            return (Criteria) this;
        }

        public Criteria andResultInfoNotBetween(String value1, String value2) {
            addCriterion("RESULT_INFO not between", value1, value2, "resultInfo");
            return (Criteria) this;
        }

        public Criteria andDescInfoIsNull() {
            addCriterion("DESC_INFO is null");
            return (Criteria) this;
        }

        public Criteria andDescInfoIsNotNull() {
            addCriterion("DESC_INFO is not null");
            return (Criteria) this;
        }

        public Criteria andDescInfoEqualTo(String value) {
            addCriterion("DESC_INFO =", value, "descInfo");
            return (Criteria) this;
        }

        public Criteria andDescInfoNotEqualTo(String value) {
            addCriterion("DESC_INFO <>", value, "descInfo");
            return (Criteria) this;
        }

        public Criteria andDescInfoGreaterThan(String value) {
            addCriterion("DESC_INFO >", value, "descInfo");
            return (Criteria) this;
        }

        public Criteria andDescInfoGreaterThanOrEqualTo(String value) {
            addCriterion("DESC_INFO >=", value, "descInfo");
            return (Criteria) this;
        }

        public Criteria andDescInfoLessThan(String value) {
            addCriterion("DESC_INFO <", value, "descInfo");
            return (Criteria) this;
        }

        public Criteria andDescInfoLessThanOrEqualTo(String value) {
            addCriterion("DESC_INFO <=", value, "descInfo");
            return (Criteria) this;
        }

        public Criteria andDescInfoLike(String value) {
            addCriterion("DESC_INFO like", value, "descInfo");
            return (Criteria) this;
        }

        public Criteria andDescInfoNotLike(String value) {
            addCriterion("DESC_INFO not like", value, "descInfo");
            return (Criteria) this;
        }

        public Criteria andDescInfoIn(List<String> values) {
            addCriterion("DESC_INFO in", values, "descInfo");
            return (Criteria) this;
        }

        public Criteria andDescInfoNotIn(List<String> values) {
            addCriterion("DESC_INFO not in", values, "descInfo");
            return (Criteria) this;
        }

        public Criteria andDescInfoBetween(String value1, String value2) {
            addCriterion("DESC_INFO between", value1, value2, "descInfo");
            return (Criteria) this;
        }

        public Criteria andDescInfoNotBetween(String value1, String value2) {
            addCriterion("DESC_INFO not between", value1, value2, "descInfo");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("CREATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("CREATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("CREATED_BY =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("CREATED_BY <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("CREATED_BY >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("CREATED_BY >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("CREATED_BY <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("CREATED_BY <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("CREATED_BY like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("CREATED_BY not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("CREATED_BY in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("CREATED_BY not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("CREATED_BY between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("CREATED_BY not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("CREATED_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("CREATED_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("CREATED_DATE =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("CREATED_DATE <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("CREATED_DATE >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED_DATE >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("CREATED_DATE <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATED_DATE <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("CREATED_DATE in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("CREATED_DATE not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("CREATED_DATE between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATED_DATE not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNull() {
            addCriterion("UPDATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNotNull() {
            addCriterion("UPDATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByEqualTo(String value) {
            addCriterion("UPDATED_BY =", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotEqualTo(String value) {
            addCriterion("UPDATED_BY <>", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThan(String value) {
            addCriterion("UPDATED_BY >", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATED_BY >=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThan(String value) {
            addCriterion("UPDATED_BY <", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThanOrEqualTo(String value) {
            addCriterion("UPDATED_BY <=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLike(String value) {
            addCriterion("UPDATED_BY like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotLike(String value) {
            addCriterion("UPDATED_BY not like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIn(List<String> values) {
            addCriterion("UPDATED_BY in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotIn(List<String> values) {
            addCriterion("UPDATED_BY not in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByBetween(String value1, String value2) {
            addCriterion("UPDATED_BY between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotBetween(String value1, String value2) {
            addCriterion("UPDATED_BY not between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIsNull() {
            addCriterion("UPDATED_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIsNotNull() {
            addCriterion("UPDATED_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateEqualTo(Date value) {
            addCriterion("UPDATED_DATE =", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotEqualTo(Date value) {
            addCriterion("UPDATED_DATE <>", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateGreaterThan(Date value) {
            addCriterion("UPDATED_DATE >", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATED_DATE >=", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateLessThan(Date value) {
            addCriterion("UPDATED_DATE <", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATED_DATE <=", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIn(List<Date> values) {
            addCriterion("UPDATED_DATE in", values, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotIn(List<Date> values) {
            addCriterion("UPDATED_DATE not in", values, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateBetween(Date value1, Date value2) {
            addCriterion("UPDATED_DATE between", value1, value2, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATED_DATE not between", value1, value2, "updatedDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 13 08:08:31 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}