package com.johnny.mybatis.mapper;

import com.johnny.mybatis.pojo.ExternalLogInfo;
import com.johnny.mybatis.pojo.ExternalLogInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ExternalLogInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    int countByExample(ExternalLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    int deleteByExample(ExternalLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    int deleteByPrimaryKey(String idAmlm2ExternalLog);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    int insert(ExternalLogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    int insertSelective(ExternalLogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    List<ExternalLogInfo> selectByExample(ExternalLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    ExternalLogInfo selectByPrimaryKey(String idAmlm2ExternalLog);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    int updateByExampleSelective(@Param("record") ExternalLogInfo record, @Param("example") ExternalLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    int updateByExample(@Param("record") ExternalLogInfo record, @Param("example") ExternalLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    int updateByPrimaryKeySelective(ExternalLogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMLM2_EXTERNAL_LOG_INFO
     *
     * @mbggenerated Sat Apr 13 08:08:31 CST 2024
     */
    int updateByPrimaryKey(ExternalLogInfo record);
}